# Generated by Django 3.2.8 on 2024-09-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Item',
        ),
    ]
