# Generated by Django 4.2.16 on 2024-09-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_trade_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='trade',
        ),
        migrations.AddField(
            model_name='trade',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.review'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.IntegerField(choices=[('Code 0', '交易中'), ('Code 1', '交易成功'), ('Code 2', '交易取消'), ('Code 3', '等待交易')], default=3),
        ),
    ]
