# Generated by Django 4.2.16 on 2024-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_rename_owner_trade_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.IntegerField(choices=[('Code 0', '交易中'), ('Code 1', '交易成功'), ('Code 2', '交易取消'), ('Code 3', '等待交易')], default='Code 3'),
        ),
    ]
