# Generated by Django 4.2.16 on 2024-09-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_alter_trade_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('Code_0', '交易中'), ('Code_1', '交易成功'), ('Code_2', '交易取消'), ('Code_3', '等待交易')], default='Code_3', max_length=50),
        ),
    ]
