# Generated by Django 4.2.16 on 2024-09-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_alter_trade_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='buyer',
        ),
    ]
