# Generated by Django 4.2.16 on 2024-09-23 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_remove_trade_buyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewForItem',
        ),
        migrations.AddField(
            model_name='trade',
            name='unReciveError',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('Code_0', '撤销'), ('Code_1', '初始化'), ('Code_2', '购买'), ('Code_3', '出售'), ('Code_4', '拒绝'), ('Code_5', '完成')], default='Code_3', max_length=50),
        ),
        migrations.CreateModel(
            name='ReviewForTrade',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='demo.trade')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('content', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.chatroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.reviewfortrade'),
        ),
    ]
