# Generated by Django 4.2.16 on 2024-09-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_rename_review_reviewforitem_trade_unreciveerror_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='name',
        ),
    ]
