# Generated by Django 4.2.16 on 2024-09-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_rename_item_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item',
        ),
    ]
