# Generated by Django 4.2.16 on 2024-09-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_rename_name_item_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='name',
        ),
    ]
