# Generated by Django 4.2.16 on 2024-09-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_rename_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buyers',
            field=models.CharField(choices=[('User', 'hzh'), ('User', 'oopq'), ('User', 'oopz'), ('default', 'default')], default='default', max_length=50),
        ),
    ]
