# Generated by Django 4.2.16 on 2024-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_alter_trade_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buyers',
            field=models.CharField(choices=[('hzh', 'hzh'), ('oopq', 'oopq'), ('oopz', 'oopz'), ('', '---------')], default='', max_length=50),
        ),
    ]
