# Generated by Django 4.2.16 on 2024-09-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_alter_trade_buyers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='buyers',
            new_name='buyer',
        ),
    ]
