# Generated by Django 4.2.16 on 2024-09-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_rename_buyers_trade_buyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
    ]
