# Generated by Django 4.2.16 on 2024-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_rename_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', to='demo.profile'),
        ),
    ]
